---
- name: Import TorrentCleanup.py
  copy: "src=TorrentCleanup.py dest={{mnt.docker_data}}/scripts/torrent/TorrentCleanup.py force=yes owner={{user}} group={{user}} mode=0775"

- name: Check arrpush.sh exists
  stat:
    path: "{{mnt.docker_data}}/scripts/torrent/arrpush.sh"
    get_attributes: false
    get_checksum: false
    get_md5: false
    get_mime: false
  register: arrpush_script

- name: Import arrpush.sh
  template:
    src: arrpush.sh.js2
    dest: "{{mnt.docker_data}}/scripts/torrent/arrpush.sh"
    owner: "{{user}}"
    group: "{{user}}"
    mode: 0775
    force: yes
  when: arrpush_script.stat.exists == False

- name: Import plex_token.sh
  copy: "src=plex_token.sh dest={{mnt.docker_data}}/scripts/plex/plex_token.sh force=yes owner={{user}} group={{user}} mode=0775"

- name: Import revoke_certs.sh
  template:
    src: revoke_certs.sh.js2
    dest: "{{mnt.docker_data}}/scripts/nginx/revoke_certs.sh"
    owner: "{{user}}"
    group: "{{user}}"
    mode: 0775
    force: yes

- name: Check cloudflared.py exists
  stat:
    path: /opt/scripts/cloudflare/cloudflared.py
    get_attributes: false
    get_checksum: false
    get_md5: false
    get_mime: false
  register: cloudflare_script

- name: Import cloudflared.py
  copy: "src=cloudflared.py dest=/opt/scripts/cloudflare/cloudflared.py force=yes owner={{user}} group={{user}} mode=0775"
  when: cloudflare_script.stat.exists == False

- name: Import plex_autoscan_url.sh
  copy: "src=plex_autoscan_url.sh dest=/opt/scripts/plex_autoscan/plex_autoscan_url.sh force=yes owner={{user}} group={{user}} mode=0775"

- name: Import restart_containers.sh
  copy: "src=restart_containers.sh dest=/opt/scripts/docker/restart_containers.sh force=yes owner={{user}} group={{user}} mode=0775"

- name: Check frontail_custom_preset.json exists
  stat:
    path: /opt/scripts/frontail/frontail_custom_preset.json
    get_attributes: false
    get_checksum: false
    get_md5: false
    get_mime: false
  register: frontail_preset

- name: Import frontail_custom_preset.json
  copy: "src=frontail_custom_preset.json dest=/opt/scripts/frontail/frontail_custom_preset.json force=yes owner={{user}} group={{user}} mode=0775"
  when: frontail_preset.stat.exists == False
