---
- name: Stop and remove any existing container
  docker_container:
    name: plexrequests
    state: absent

- name: Setup default plexrequests docker volume to be merged
  set_fact:
    plexrequests_volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "{{mnt.docker_data}}/plexrequests:/config"

- name: Create and start container
  docker_container:
    name: plexrequests
    image: "linuxserver/plexrequests"
    pull: yes
    published_ports:
      - "127.0.0.1:3000:3000"
    env:
      PUID: "{{uid.stdout}}"
      PGID: "{{gid.stdout}}"
      VIRTUAL_HOST: "plexrequests.{{domain}}"
      VIRTUAL_PORT: 3000
      LETSENCRYPT_HOST: "plexrequests.{{domain}}"
      LETSENCRYPT_EMAIL: "{{email}}"
    volumes: "{{plexrequests_volumes + docker_volumes.plexrequests|default([])}}"
    networks:
      - name: cloudbox
        ipv4_address: 172.18.0.17
        aliases:
          - plexrequests
    restart_policy: always
    state: started
