---

- name: "Get ansible-playbook binary path"
  shell: "which ansible-playbook"
  register: playbook_binary
  
- name: "Schedule cron backup for GCE Syn state: {{backup.cron_state}}, when: {{backup.cron_time}}"
  cron:
    name: "Daily GCE Sync"
    special_time: "{{gce_cron}}"
    job: "{{playbook_binary.stdout}} {{playbook_dir}}/cloudbox.yml --tags gce"
    state: "{{backup.cron_state}}"
    
- name: Start GCE
  gce:
    instance_names: "{{gce.name}}"
    zone: "{{gce.zone}}"
    state: started
    credentials_file: "{{ gce.credentials_file }}"
    service_account_email: "{{gce.service_account_email}}"
    project_id: "{{gce.project_id}}"
    