# Place this file in the users home dir as .settings.yml
# Ideally ansible-vault encrypted
plex_user: PLEXUSER
plex_pass: PASS
plex_autoscan_pass: PASS
user_pass: password123
user_domain: mydomain.com
user_email: my@email.com
cloudflare_token: MYTOKEN
telly_m3u_url: http://m3u.com
telly_epg_url: http://epg.com
gce_name: my-test-instance1
gce_zone: us-central1-a
gce_credentials_file: "/path/to/your-key.json"
gce_service_account_email: "your-sa@your-project-name.iam.gserviceaccount.com"
gce_project_id: "your-project-name"
gce_json: |
  blah
  blah
vpn_secretkey: vpnkey
vpn_user: vpnuser
vpn_pass: vpnpass
