---
skip_commits:
  files:
    - '*.md'
    - 'settings.yml.default'
    - 'roles/scripts/files/*'

image: ubuntu

init:
  - sh: curl -s https://cloudbox.rocks/install_dependencies.sh | sudo -H sh

install:
  - sh: sudo ansible-playbook /home/appveyor/projects/cloudbox/cloudbox.yml --syntax-check
  - sh: sudo ansible-playbook /home/appveyor/projects/cloudbox/cloudbox.yml --tags "full" --skip-tags "update-settings" --extra-vars "continuous_integration=true"

matrix:
  fast_finish: true

# to disable automatic builds
build: off
