---
- hosts: localhost
  become: True
  vars_files:
    - settings.yml
    - "/home/seed/.settings.yml"
    - bootstrap.yml
  roles:
    - role: "{{roles_dir}}/common"
      tags: common
    - role: "{{roles_dir}}/cloudbox"
      tags: cloudbox


