---

- name: "Get {{user}} uid"
  shell: "id -u {{user}}"
  register: uid

- name: "Get {{user}} gid"
  shell: "id -g {{user}}"
  register: gid


- name: "Assert that all Telly related settings are filled in."
  assert:
    that:
      - (telly.playlist is defined) and (telly.playlist is not none) and not (telly.playlist | trim == '') and (telly.playlist != "/opt/telly/file.m3u or URL2M3U")
      - (telly.streams is defined) and (telly.streams is not none) and not (telly.streams | trim == '')
    msg: "You must specify the Telly settings in 'adv_settings.yml'"

- name: Stop and remove any existing container
  docker_container:
    name: "{{role_name}}"
    state: absent

- name: Create telly directories
  file: "path={{item}} state=directory mode=0775 owner={{user}} group={{user}}"
  with_items:
    - "{{role_dir}}"

- name: Setup default telly docker volume to be merged
  set_fact:
    telly_volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "{{role_dir}}:{{role_dir}}"

- name: Create and start container
  docker_container:
    name: "{{role_name}}"
    image: "tombowditch/telly"
    pull: yes
    volumes: "{{telly_volumes + docker_volumes.telly|default([])}}"
    env:
      PLAYLIST: "{{ telly_m3u_url }}"
      STREAMS: "{{telly.streams}}"
      LISTEN: "{{telly.listen}}"
      PUID: "{{uid.stdout}}"
      PGID: "{{gid.stdout}}"
    networks:
      - name: cloudbox
        aliases:
          - "{{role_name}}"
    restart_policy: always
    state: started