---
- name: "Get {{user}} uid"
  shell: "id -u {{user}}"
  register: uid

- name: "Get {{user}} gid"
  shell: "id -g {{user}}"
  register: gid

- name: Create nginx-proxy directories
  file: "path={{item}} state=directory mode=0775 owner={{user}} group={{user}} recurse=true"
  with_items:
    - "{{mnt.docker_data}}/nginx-proxy"

- include: htauth.yml
  when: http_auth.enable | default(False)
  
- name: Import proxy.conf
  copy: "src=proxy.conf dest={{mnt.docker_data}}/nginx-proxy/proxy.conf force=yes owner={{user}} group={{user}} mode=0775"

- name: Stop and remove any existing container
  docker_container:
    name: nginx-proxy
    state: absent

- name: Stop and remove any existing letsencrypt container
  docker_container:
    name: letsencrypt
    state: absent

- name: Setup default nginx-proxy docker volume to be merged
  set_fact:
    nginx_proxy_volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "{{mnt.docker_data}}/nginx-proxy:/etc/nginx/certs:ro"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "{{mnt.docker_data}}/nginx-proxy/htpasswd:/etc/nginx/htpasswd"
      - "/etc/nginx/vhost.d"
      - "/usr/share/nginx/html"

- name: Create and start container
  docker_container:
    name: nginx-proxy
    image: "jwilder/nginx-proxy@sha256:76d9ed11c131fadc7546e3b9b085970e13ff45186171b975ad60830f5ca0d689" 
    pull: yes
    published_ports:
      - "80:80"
      - "443:443"
    volumes: "{{nginx_proxy_volumes + docker_volumes.nginx_proxy|default([])}}"
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    networks:
      - name: cloudbox
        aliases:
          - nginx-proxy
    restart_policy: always
    state: started

- name: Setup default letsencrypt docker volume to be merged
  set_fact:
    letsencrypt_volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "{{mnt.docker_data}}/nginx-proxy:/etc/nginx/certs:rw"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

- name: Create and start letsencrypt container
  docker_container:
    name: letsencrypt
    image: "jrcs/letsencrypt-nginx-proxy-companion"
    pull: yes
    volumes: "{{letsencrypt_volumes + docker_volumes.letsencrypt|default([])}}"
    volumes_from:
      - "nginx-proxy"
    env:
      DEBUG: true
    networks:
      - name: cloudbox
        aliases:
          - letsencrypt
    restart_policy: always
    state: started
