---
# Disable ipv6 via sysctl
- name: disable ipv6 network
  sysctl: >
    name={{ item }}
    value=1
    sysctl_set=yes
  with_items:
    - net.ipv6.conf.default.disable_ipv6
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv6.conf.lo.disable_ipv6
  