---
- name: Install required packages
  apt: "name={{item}} state=installed"
  with_items:
    - lsb-release
    - figlet
    - update-motd
    - update-notifier

- name: Remove existing motd
  file: "path={{item}} state=absent"
  with_items:
    - /etc/update-motd.d
    - /etc/motd
    - /etc/motd.dynamic

- name: Create dynamic motd directory
  file:
    path: /etc/update-motd.d
    state: directory
    mode: 0775

- name: Import dynamic motd files 
  copy: "src={{item}} dest=/etc/update-motd.d/{{item}} force=yes mode=0775"
  with_items:
    - 00-header
    - 10-sysinfo
    - 90-footer
