---
- name: "Get {{user}} uid"
  shell: "id -u {{user}}"
  register: uid

- name: "Get {{user}} gid"
  shell: "id -g {{user}}"
  register: gid

- name: Stop and remove any existing container
  docker_container:
    name: radarr
    state: absent
    
- name: Create radarr directories
  file: "path={{item}} state=directory mode=0775 owner={{user}} group={{user}}"
  with_items:
    - "{{mnt.docker_data}}/radarr"
    - "{{mnt.local}}/Media/Kids Movies"
    - "{{mnt.local}}/Media/Music"

- name: Setup default radarr docker volume to be merged
  set_fact:
    radarr_volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "{{mnt.docker_data}}/radarr:/config"

- name: Create and start container
  docker_container:
    name: radarr
    image: hotio/suitarr
    pull: yes
    published_ports:
      - "127.0.0.1:7878:8080"
    env:
      APP: "radarr"
      VERSION: "unstable"
      PUID: "{{uid.stdout}}"
      PGID: "{{gid.stdout}}"
      BACKUP: "no"
      MONO_TLS_PROVIDER: legacy
      VIRTUAL_HOST: "radarr.{{domain}}"
      VIRTUAL_PORT: 8080
      LETSENCRYPT_HOST: "radarr.{{domain}}"
      LETSENCRYPT_EMAIL: "{{email}}"
    volumes: "{{radarr_volumes + docker_volumes.radarr|default([])}}"    
    networks:
      - name: cloudbox
        aliases:
          - radarr
    restart_policy: always
    state: started
