---
  
- name: Create htpasswd
  htpasswd:
    path: "{{mnt.docker_data}}/nginx-proxy/htpasswd/{{ item }}.{{ domain }}"
    name: "{{user}}"
    password: "{{passwd}}"
    owner: "{{user}}"
    group: "{{user}}"
    mode: 0664
  with_items: 
    - "{{ http_auth.sites }}"
