---
- name: Verify that Rclone version was specified
  fail: msg="You must specify the Rclone version in settings.yml"
  when: (
      (rclone.version is undefined)
      or
      (rclone.version is none)
      or
      (rclone.version | trim == '')
      )

- include_tasks: "{{roles_dir}}/resource/get-id/tasks/main.yml"

- name: "Install rclone version: latest"
  apt:
    deb: https://downloads.rclone.org/rclone-current-linux-amd64.deb
  when:  rclone.version == 'latest' 

- name: "Install rclone version: {{rclone.version}}"
  apt:         
    deb: https://downloads.rclone.org/v{{rclone.version}}/rclone-v{{rclone.version}}-linux-amd64.deb
  when:  rclone.version != 'latest'
    
- name: Ensure rclone folders exists
  file: "path={{item}} state=directory mode=0775 owner={{user}} group={{user}} recurse=true"
  with_items:
    - "{{mnt.docker_data}}/rclone"
    - "/home/{{user}}/.config/rclone"

- name: Symlink config
  file:
    src: "{{mnt.docker_data}}/rclone/rclone.conf"
    dest: "/home/{{user}}/.config/rclone/rclone.conf"
    owner: "{{user}}"
    group: "{{user}}"
    state: link
    force: yes

- name: Check restore rclone.conf exists
  stat:
    path: "{{playbook_dir}}/rclone.conf"
  register: restore_rclone_conf

- name: Restore rclone.conf as part of restore process
  copy:
    src: "{{playbook_dir}}/rclone.conf"
    dest: "{{mnt.docker_data}}/rclone/rclone.conf"
    mode: 0775
    owner: "{{user}}"
    group: "{{user}}"
  when: restore_rclone_conf.stat.exists

- name: Remove restored rclone.conf
  file:
    path: "{{playbook_dir}}/rclone.conf"
    state: absent
  when: restore_rclone_conf.stat.exists
