---
- name: "Get {{user}} uid"
  shell: "id -u {{user}}"
  register: uid

- name: "Get {{user}} gid"
  shell: "id -g {{user}}"
  register: gid

- name: Stop and remove any existing container
  docker_container:
    name: sonarr
    state: absent

- name: Create sonarr directories
  file: "path={{item}} state=directory mode=0775 owner={{user}} group={{user}}"
  with_items:
    - "{{mnt.docker_data}}/sonarr"
    - "{{mnt.local}}/Media/TV"
    - "{{mnt.local}}/Media/Kids TV"
    
- name: Setup default sonarr docker volume to be merged
  set_fact:
    sonarr_volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "{{mnt.docker_data}}/sonarr:/config"
      - "{{mnt.docker_data}}/scripts:/scripts"

- name: Create and start container
  docker_container:
    name: sonarr
    image: "hotio/suitarr"
    pull: yes
    published_ports:
      - "127.0.0.1:8989:8080"
    env:
      APP: "sonarr"
      VERSION: "unstable"
      BACKUP: "no"
      PUID: "{{uid.stdout}}"
      PGID: "{{gid.stdout}}"
      MONO_TLS_PROVIDER: legacy
      VIRTUAL_HOST: "sonarr.{{domain}}"
      VIRTUAL_PORT: 8080
      LETSENCRYPT_HOST: "sonarr.{{domain}}"
      LETSENCRYPT_EMAIL: "{{email}}"
    volumes: "{{sonarr_volumes + docker_volumes.sonarr|default([])}}"
    networks:
      - name: cloudbox
        aliases:
          - sonarr
    restart_policy: always
    state: started
