#########################################################################
# Title:         Cloudbox: Sonarr Role                                  #
# Author(s):     l3uddz                                                 #
# URL:           https://github.com/Cloudbox/Cloudbox                   #
# Docker Image:  hotio/suitarr                                          #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.rocks          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Setting CloudFlare DNS Record"
  include_role:
    name: cloudflare
  vars:
    subdomain: sonarr

- name: "Get {{user}} uid"
  shell: "id -u {{user}}"
  register: uid

- name: "Get {{user}} gid"
  shell: "id -g {{user}}"
  register: gid

- name: Stop and remove any existing container
  docker_container:
    name: "{{role_name}}"
    state: absent

- name: Create sonarr directories
  file: "path={{item}} state=directory mode=0775 owner={{user}} group={{user}}"
  with_items:
    - "{{role_dir}}"

- name: Setup default sonarr docker volume to be merged
  set_fact:
    sonarr_volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "{{role_dir}}:/config"

- name: Create and start container
  docker_container:
    name: "{{role_name}}"
    image: "hotio/suitarr"
    pull: yes
    published_ports:
      - "127.0.0.1:8989:8080"
    env:
      APP: "sonarr"
      VERSION: "unstable"
      BACKUP: "no"
      PUID: "{{uid.stdout}}"
      PGID: "{{gid.stdout}}"
      MONO_TLS_PROVIDER: legacy
      VIRTUAL_HOST: "sonarr.{{domain}}"
      VIRTUAL_PORT: 8080
      LETSENCRYPT_HOST: "sonarr.{{domain}}"
      LETSENCRYPT_EMAIL: "{{email}}"
    volumes: "{{sonarr_volumes + docker_volumes.sonarr|default([])}}"
    networks:
      - name: cloudbox
        aliases:
          - "{{role_name}}"
    restart_policy: always
    state: started
