#########################################################################
# Title:         Cloudbox: Plex Patrol Role                             #
# Author(s):     l3uddz                                                 #
# URL:           https://github.com/Cloudbox/Cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.rocks          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Get {{user}} uid"
  shell: "id -u {{user}}"
  register: uid

- name: "Get {{user}} gid"
  shell: "id -g {{user}}"
  register: gid

- import_tasks: ../cloudbox/roles/common/tasks/plexauth.yml
  tags: plexauth

- name: Stop and remove any existing container
  docker_container:
    name: "{{role_name}}"
    state: absent

- name: Create plex_patrol directories
  file: "path={{item}} state=directory mode=0775 owner={{user}} group={{user}}"
  with_items:
    - "{{role_dir}}"

- name: Check config exists
  stat:
    path: "{{role_dir}}/settings.ini"
  register: plex_patrol_config

- name: Import default config
  template:
    src: settings.ini
    dest: "{{role_dir}}/settings.ini"
    force: yes
  when: plex_patrol_config.stat.exists == False

- name: Create and start container
  docker_container:
    name: "{{role_name}}"
    image: "cloudb0x/plex_patrol:latest"
    pull: yes
    user: "{{uid.stdout}}:{{gid.stdout}}"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "{{role_dir}}:/config"
    networks:
      - name: cloudbox
        aliases:
          - "{{role_name}}"
    restart_policy: always
    state: started
