---
  
- include_tasks: "{{roles_dir}}/resource/get-id/tasks/main.yml"
  tags: get_id
  
- name: Stop and remove any existing container
  docker_container:
    name: watchtower
    state: absent

- name: Setup default watchtower docker volume to be merged
  set_fact:
    watchtower_volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"

- name: Create and start container
  docker_container:
    name: watchtower
    image: "v2tec/watchtower"
    command: '{{watchtower.command + watchtower.monitor}}'
    volumes: "{{watchtower_volumes + docker_volumes.watchtower|default([])}}"
    restart_policy: always
    networks:
      - name: cloudbox
        aliases:
          - watchtower
    state: started
