---
- name: Stop and remove any existing container
  docker_container:
    name: jackett
    state: absent

- name: Setup default jackett docker volume to be merged
  set_fact:
    jackett_volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "{{mnt.docker_data}}/jackett:/config"

- name: Create and start container
  docker_container:
    name: jackett
    image: hotio/suitarr
    pull: yes
    published_ports:
      - "127.0.0.1:9117:8080"
    env:
      APP: "jackett"
      VERSION: "unstable"
      BACKUP: "no"
      PUID: "{{uid.stdout}}"
      PGID: "{{gid.stdout}}"
      VIRTUAL_HOST: "jackett.{{domain}}"
      VIRTUAL_PORT: 8080
      LETSENCRYPT_HOST: "jackett.{{domain}}"
      LETSENCRYPT_EMAIL: "{{email}}"
    volumes: "{{jackett_volumes + docker_volumes.jackett|default([])}}"
    restart_policy: always
    state: started
    networks:
      - name: cloudbox
        ipv4_address: 172.18.0.11
        aliases:
          - jackett
