---
  - name: Check service exists
    stat:
      path: "/etc/systemd/system/unionfs.service"
    register: unionfs_service

  - name: Stop existing unionfs service
    systemd: 
      state: stopped 
      name: unionfs
    when: unionfs_service.stat.exists
    
  - name: Install fuse
    apt: 
      name: fuse
      state: installed

  - name: Import fuse.conf
    copy: 
      src: fuse.conf
      dest: /etc/fuse.conf
      force: yes

  - name: Install unionfs
    apt: 
      name: unionfs-fuse
      state: installed

  - name: Import unionfs.service
    template: 
      src: unionfs.service.js2
      dest: /etc/systemd/system/unionfs.service 
      force: yes
    when: unionfs_service.stat.exists == False

  - name: Create {{mnt.unionfs}}
    file: 
      path: "{{item}}"
      state: directory
      mode: 0775
      owner: "{{user}}"
      group: "{{user}}"
    with_items:
      - "{{mnt.unionfs}}"

  - name: Start unionfs service
    systemd: 
      state: started
      name: unionfs
      daemon_reload: yes
      enabled: yes
