---
- block:
  - name: "Check if backup.lock is present"
    stat:
      path: "{{playbook_dir}}/backup.lock"
    register: backup_lock

  - name: "Fail when backup.lock exists"
    fail:
      msg: "Backup is already in progress..."
    when: backup_lock.stat.exists

  - name: "Create backup.lock"
    file:
      path: "{{playbook_dir}}/backup.lock"
      state: touch
      owner: "{{user}}"
      group: "{{user}}"
      mode: 0775
    when: backup_lock.stat.exists == False

  - name: "Get Start Time"
    set_fact: start_time="{{lookup('pipe','date \"+%s\"')}}"

  - name: "Pushover Message: Started Cloudbox backup task."
    pushover:
      msg: "Started Cloudbox backup task."
      app_token: "{{backup.pushover_app_token}}"
      user_key: "{{backup.pushover_user_key}}"
    when: not(
        (backup.pushover_app_token is undefined)
        or
        (backup.pushover_app_token is none)
        or
        (backup.pushover_app_token | trim == '')
        or
        (backup.pushover_user_key is undefined)
        or
        (backup.pushover_user_key is none)
        or
        (backup.pushover_user_key | trim == '')
      )

  - name: "Check {{backup.dest}} exists"
    stat:
      path: "{{backup.dest}}"
    register: backup_location

  - name: "Create backup location {{backup.dest}}"
    file:
      path: "{{backup.dest}}"
      state: directory
      owner: "{{user}}"
      group: "{{user}}"
      mode: 0775
      recurse: yes
    when: backup_location.stat.exists == False

  - name: "Copy files to \"{{backup.dest}}\""
    copy:
      src: "{{item}}"
      dest: "{{backup.dest}}"
      owner: "{{user}}"
      group: "{{user}}"
      mode: 0775
      force: yes
    with_items:
     - "{{playbook_dir}}/settings.yml"
     - "/home/{{user}}/.config/rclone/rclone.conf"

  - name: "Check {{backup.dest}}/cloudbox.tar exists"
    stat:
      path: "{{backup.dest}}/cloudbox.tar"
      get_attributes: false
      get_checksum: false
      get_md5: false
      get_mime: false
    register: backup_previous

  # Use mv because Ansible copy & delete takes a lot longer.
  - name: "Moving cloudbox.tar to cloudbox.tar.backup"
    shell: "mv '{{backup.dest}}/cloudbox.tar' '{{backup.dest}}/cloudbox.tar.backup'"
    when: backup_previous.stat.exists

  - name: "Remove previous cloudbox.tar"
    file:
      path: "{{backup.dest}}/cloudbox.tar"
      state: absent
    when: backup_previous.stat.exists

  - name: "Copy settings files to {{mnt.docker_data}} for inclusion in backup"
    copy:
      src: "{{item}}"
      dest: "{{mnt.docker_data}}/{{item |basename}}"
      force: yes
      owner: "{{user}}"
      group: "{{user}}"
      mode: 0775
    with_items:
      - "{{playbook_dir}}/settings.yml"
      - "{{ ansible_env.HOME }}/.settings.yml"

  - name: list running containers
    shell: "docker ps -q"
    register: docker_list

  - name: "Copy /etc/systemd/system to {{mnt.docker_data}}/systemd for inclusion in backup"
    copy:
      src: "/etc/systemd/system/{{item}}"
      dest: "{{mnt.docker_data}}/systemd/{{item}}"
      force: yes
      group: "{{user}}"
      owner: "{{user}}"
      mode: 0775
    with_items:
      - plexdrive.service
      - unionfs_cleaner.service
      - plex_autoscan.service
      - unionfs.service

  - name: "Pushover Message: Stopped Cloudbox containers."
    pushover:
      msg: "Stopped Cloudbox containers."
      app_token: "{{backup.pushover_app_token}}"
      user_key: "{{backup.pushover_user_key}}"
    when: not(
        (backup.pushover_app_token is undefined)
        or
        (backup.pushover_app_token is none)
        or
        (backup.pushover_app_token | trim == '')
        or
        (backup.pushover_user_key is undefined)
        or
        (backup.pushover_user_key is none)
        or
        (backup.pushover_user_key | trim == '')
      )

  - name: "Stop all previously running containers"
    shell: "docker stop {{docker_list.stdout| replace('\n', ' ')}}"
    ignore_errors: yes

  - name: Stop unionfs_cleaner and plexdrive
    systemd:
      name: "{{item}}"
      state: stopped
    with_items:
      - 'unionfs_cleaner'
      - 'plexdrive'

  - name: "Archiving {{mnt.docker_data}} to {{backup.dest}}/cloudbox.tar"
    shell: "tar -cf '{{backup.dest}}/cloudbox.tar' -C {{mnt.docker_data}} ."

  - name: "Get new {{backup.dest}}/cloudbox.tar stats"
    stat:
      path: "{{backup.dest}}/cloudbox.tar"
      get_attributes: false
      get_checksum: false
      get_md5: false
      get_mime: false
    register: backup_new

  - name: "Pushover Message: Backup archive created (file size: {{ ( ( backup_new.stat.size / (1024*1024*1024) ) | int | abs ) }}GB)."
    pushover:
      msg: "Backup archive created (file size: {{ ( ( backup_new.stat.size / (1024*1024*1024) ) | int | abs ) }}GB)."
      app_token: "{{backup.pushover_app_token}}"
      user_key: "{{backup.pushover_user_key}}"
    when: not(
        (backup.pushover_app_token is undefined)
        or
        (backup.pushover_app_token is none)
        or
        (backup.pushover_app_token | trim == '')
        or
        (backup.pushover_user_key is undefined)
        or
        (backup.pushover_user_key is none)
        or
        (backup.pushover_user_key | trim == '')
        or
        (backup_new is undefined)
      )

  - name: "Remove cloudbox.tar.backup from \"{{backup.dest}}\""
    file:
      path: "{{backup.dest}}/cloudbox.tar.backup"
      state: absent
    when: backup_new.stat.exists

  - name: Start plexdrive and unionfs_cleaner
    systemd:
      name: "{{item}}"
      state: started
    with_items:
      - 'plexdrive'
      - 'unionfs_cleaner'

  - name: "Wait for 5 seconds before starting containers"
    wait_for:
      timeout: 5

  - name: "Start all previously running containers"
    shell: "docker start {{docker_list.stdout| replace('\n', ' ')}}"
    ignore_errors: yes

  - name: "Pushover Message: Started Cloudbox containers."
    pushover:
      msg: "Started Cloudbox containers."
      app_token: "{{backup.pushover_app_token}}"
      user_key: "{{backup.pushover_user_key}}"
    when: not(
        (backup.pushover_app_token is undefined)
        or
        (backup.pushover_app_token is none)
        or
        (backup.pushover_app_token | trim == '')
        or
        (backup.pushover_user_key is undefined)
        or
        (backup.pushover_user_key is none)
        or
        (backup.pushover_user_key | trim == '')
      )

  - name: "Wait for 10 seconds before uploads"
    wait_for:
      timeout: 10

  - name: "Set {{backup.dest}} permissions"
    shell: "chmod -R 775 {{backup.dest}}"

  - name: "Set {{backup.dest}} owner"
    shell: "chown -R {{user}}:{{user}} {{backup.dest}}"

  # Reset permissions; reset mod dates to avoid conflicts during rclone backup.
  - name: "Touch and set permissions to {{backup.dest}}"
    file:
      path: "{{backup.dest}}"
      state: touch
      owner: "{{user}}"
      group: "{{user}}"
      mode: 0755
      recurse: yes

  # Due to a previously ran touch command, all files have same mod dates, therefore, only one file's mod date is needed.
  - name: "Get datestamp for previous \"{{backup.rclone_dest}}/cloudbox.tar\""
    shell: "rclone lsl {{ backup.rclone_dest }}/cloudbox.tar | cut -d ' ' -f 2,3 | cut -d '.' -f 1 | sed s/' '/_/g | sed s/':'/./g"
    register: rclone_timestamp
    ignore_errors: yes
    when: backup.use_rclone

  # If rclone_timestamp is blank (would happen if cloudbox.tar did not exist), default the naming of other files to 'filename.old.ext'.
  - name: "Archive previous files in \"{{backup.rclone_dest}}/\""
    shell: "rclone lsl '{{ backup.rclone_dest }}/{{ item }}' '{{ backup.rclone_dest }}/{{ (item | splitext)[0] }}.{{ rclone_timestamp.stdout | default('old', true) }}{{ (item | splitext)[1] }}' 2>/dev/null"
    ignore_errors: yes
    when: backup.use_rclone
    with_items:
     - "settings.yml"
     - "rclone.conf"
     - "cloudbox.tar"

  - name: "Upload backup with rclone to \"{{backup.rclone_dest}}\""
    command: "rclone copy '{{backup.dest}}' '{{backup.rclone_dest}}' --stats=30s -v --transfers=2 --drive-chunk-size=64M --log-file='/home/{{user}}/backup_rclone.log'"
    become: true
    become_user: "{{user}}"
    when: backup.use_rclone

  - name: "Pushover Message: Uploaded backup with rclone to \"{{backup.rclone_dest}}\"."
    pushover:
      msg: "Uploaded backup with rclone to \"{{backup.rclone_dest}}\"."
      app_token: "{{backup.pushover_app_token}}"
      user_key: "{{backup.pushover_user_key}}"
    when: not(
        (backup.pushover_app_token is undefined)
        or
        (backup.pushover_app_token is none)
        or
        (backup.pushover_app_token | trim == '')
        or
        (backup.pushover_user_key is undefined)
        or
        (backup.pushover_user_key is none)
        or
        (backup.pushover_user_key | trim == '')
        or
        (backup.use_rclone == false)
      )

  - name: "Upload backup with rsync to \"{{backup.rsync_dest}}\""
    synchronize:
      src: "{{backup.dest}}/"
      dest: "{{backup.rsync_dest}}/"
      rsync_opts:
        - "--log-file='/home/{{user}}/backup_rsync.log'"
    become: true
    become_user: "{{user}}"
    when: backup.use_rsync

  - name: "Pushover Message: Uploaded backup with rsync to \"{{backup.rsync_dest}}\"."
    pushover:
      msg: "Uploaded backup with rsync to \"{{backup.rsync_dest}}\"."
      app_token: "{{backup.pushover_app_token}}"
      user_key: "{{backup.pushover_user_key}}"
    when: not(
        (backup.pushover_app_token is undefined)
        or
        (backup.pushover_app_token is none)
        or
        (backup.pushover_app_token | trim == '')
        or
        (backup.pushover_user_key is undefined)
        or
        (backup.pushover_user_key is none)
        or
        (backup.pushover_user_key | trim == '')
        or
        (backup.use_rsync == false)
      )

  - name: "Get End Time"
    set_fact: end_time="{{lookup('pipe','date \"+%s\"')}}"

  - name: "Pushover Message: Finished Cloudbox backup task in {{  ((((end_time|int) - (start_time|int)) /60)|int|abs) }} minutes."
    pushover:
      msg: "Finished Cloudbox backup task in {{  ((((end_time|int) - (start_time|int)) /60)|int|abs) }} minutes."
      app_token: "{{backup.pushover_app_token}}"
      user_key: "{{backup.pushover_user_key}}"
    when: not(
        (backup.pushover_app_token is undefined)
        or
        (backup.pushover_app_token is none)
        or
        (backup.pushover_app_token | trim == '')
        or
        (backup.pushover_user_key is undefined)
        or
        (backup.pushover_user_key is none)
        or
        (backup.pushover_user_key | trim == '')
      )

  - name: "Remove cloudbox.tar from \"{{backup.dest}}\""
    file:
      path: "{{backup.dest}}/cloudbox.tar"
      state: absent
    when: backup_new.stat.exists and backup.keep_local_copy == False

  - name: "Get ansible-playbook binary path"
    shell: "/usr/bin/which ansible-playbook"
    register: playbook_binary

  - name: "Schedule cron backup"
    cron:
      name: "Backup Cloudbox"
      minute: "{{backup.cron_minute}}"
      hour: "{{backup.cron_hour}}"
      job: "PATH='/usr/bin:/bin:/usr/local/bin' {{playbook_binary.stdout}} {{playbook_dir}}/cloudbox.yml --tags backup"
      state: "{{backup.cron_state}}"
      
  always:
  - debug: msg="Finished backup"
    when: backup_lock.stat.exists == False

  - name: "Remove backup.lock"
    file:
      path: "{{playbook_dir}}/backup.lock"
      state: absent
    when: backup_lock.stat.exists == False
