#########################################################################
# Title:         Cloudbox: Cloudflare Role                              #
# Author(s):     l3uddz, desimaniac                                     #
# URL:           https://github.com/Cloudbox/Cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.rocks          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Get IP Address
  ipinfoio_facts:

- name: "Set DNS Record for {{subdomain}}.{{domain}} to {{ansible_default_ipv4.address}}"
  cloudflare_dns:
    account_api_token: "{{cloudflare_api_token}}"
    account_email: "{{email}}"
    zone: "{{domain}}"
    state: present
    solo: true
    proxied: no
    type: A
    value: "{{ ip }}"
    record: "{{subdomain}}"
  when: not(
      (cloudflare_api_token is undefined)
      or
      (cloudflare_api_token is none)
      or
      (cloudflare_api_token | trim == '')
    )
